#!/bin/sh

status="$(nmcli general status | grep -oh "\w*connect\w*")"

if [[ "$status" == "disconnected" ]]; then
  printf "󰖪 😿"
elif [[ "$status" == "connecting" ]]; then
  printf "󱍸 🤔"
elif [[ "$status" == "connected" ]]; then
  strength="$(python $HOME/.config/Scripts/wifi-conn-strength)"
  if [[ "$?" == "0" ]]; then
	printf "󰖩 💪"
  else
    printf "󰖪 😿"
  fi
fi
